{{- if .Values.secretsToFile.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    {{- include "hoslog.labels" . | nindent 4 }}
  name: {{ include "hoslog.fullname" . }}
spec:
  refreshInterval: {{ .Values.secretsToFile.refreshInterval | default "10s" }}
  secretStoreRef:
    name: {{ .Values.secretsToFile.secretStore.name | default "secretstore" }}
    kind: {{ .Values.secretsToFile.secretStore.kind | default "SecretStore" }}
  # {{- if .Values.envFromSecret.enabled }}
  # dataFrom:
  #   {{ include "secrets.fromSecret" . | nindent 4 }}
  # {{- end }}
  {{- if .Values.secretsToFile.enabled }}
  data:
    {{ include "secrets.fromFile" . | nindent 4 }}
  {{- end }}
{{- end }}
